### ISSUE TITLE
Torrent RSS feed support 

### ISSUE THREAD

**Issue by sorunis** [Answeror/torabot#10]
schema : http://www.bittorrent.org/beps/bep_0036.html

Sample : http://kickass.to/usearch/fargo%20category%3Atv/?rss=1

已fork, 还不太熟悉github的流程， 晚上学习下。

**Comment by Answeror** [comment]
This functionality has been implemented in feed mod. You can subscribe it in http://torabot.com/search/feed?q=http%3A%2F%2Fkickass.to%2Fusearch%2Ffargo%2520category%253Atv%2F%3Frss%3D1
