### ISSUE TITLE
yande.re/danbooru搜索提供下拉菜单抓取

### ISSUE THREAD

**Issue by unnya** [Answeror/torabot#13]
yande.re和danbooru提供了搜索输入的下拉菜单（在输入未完成的时候，提供近似结果的下拉菜单）
由于某些tag会有重复，例如akatuki，可能会有复数作品的人物叫akatuki，于是这两个搜索结果的下拉菜单当中有后缀作品名，但是这在torabot当中无法被直观的体现和获取，导致搜索结果不准确。例如我搜索shimakaze，却没有任何结果。

**Comment by Answeror** [comment]
根据[yande.re的源码](https://github.com/moebooru/moebooru/blob/0aa622f2fbdb81a19578c999775ce3bbb2fc49b2/lib/assets/javascripts/moe-legacy/tag_completion.js), 在用户键入时会ajax获取一个巨大的tag列表, 并在本地缓存: https://yande.re/tag/summary.json

计划为mod提供一个`completion_jsonp`接口, 返回jsonp字符串, 该jsonp里包含了从上述链接抓取的信息. 这个抓取本身是由一个独立的booru query method实现的, 即与其它inactive query一样(比如bilibili mod的bangumi method的实现), 不参与定时sync, 但是在查询过期时会立即sync.

不直接返回json或tag列表的原因是某些mod可能需要提供更加高级的补全机制, 无法将信息一次性传给客户端.

**Comment by Answeror** [comment]
#0194dabfb0 添加了yande.re的自动补全. 初次使用时若没有弹出下拉菜单, 请刷新页面.

**Comment by Answeror** [comment]
a122769a8ba85b691d24fd9ed1865d7f9e0288dd 添加了danbooru的自动补全, 初次输入会有大约3秒的延迟.
