### ISSUE TITLE
单订阅、网站投递上线设置

### ISSUE THREAD

**Issue by unnya** [Answeror/torabot#16]
当你的订阅列表很多的时候，稍不注意邮箱就会被占领。
建议设置单tag、单网站每日投递数量上线。
非必须开发需求。
![qq20140530141948](https://cloud.githubusercontent.com/assets/6995834/3127583/d2ed96dc-e7c2-11e3-9522-0f4a1bd3b3cb.jpg)

**Comment by Answeror** [comment]
我自己也遇到过这样的问题, 但是总觉得设数量限制导致漏了重要的通知也不太好.
我的计划是当超过用户设定的某个阈值后, 就把多个通知放到一封邮件里, 做成一个digest.

**Comment by Answeror** [comment]
Done in `0.4.3`. Limit notice sending rate, and aggregate multiple notices into one email.
