### ISSUE TITLE
希望能设置通知频率

### ISSUE THREAD

**Issue by septs** [Answeror/torabot#26]
比如
1. **3小时通知一次**
2. **6小时通知一次**
3. **12小时通知一次**
4. **24小时通知一次**
当然希望最好支持"crontab"限制最短周期1小时

**Comment by Answeror** [comment]
现在的周期是5分钟一次. 当通知过于频繁时, 会自动合并多个通知一起发送. 如果合并通知导致邮件过大, 就会省略部分通知, 并在邮件里注明"省略部分通知"字样...

当然在用户设置里加入自定义频率也是可以的.
